name: Cypress Tests

env:
  VITE_APP_FIREBASE_API_KEY: AIzaSyC_va_jZUMV13i7--ni9J6Sn-2EHYyIdP8
  VITE_APP_AUTH_DOMAIN: codelabz-2402c.firebaseapp.com
  VITE_APP_FIREBASE_PROJECT_ID: codelabz-2402c
  VITE_APP_FIREBASE_MESSAGING_SENDER_ID: 229958124506
  VITE_APP_FIREBASE_APP_ID: 1:229958124506:web:66e940924b9c57daf276e3
  VITE_APP_FIREBASE_MEASUREMENTID: G-4NKDVX9R23
  VITE_APP_DATABASE_URL: https://codelabz-2402c-default-rtdb.asia-southeast1.firebasedatabase.app/
  VITE_APP_FIREBASE_FCM_VAPID_KEY: BGwK_20FuPqER-t3KvXzWGwTs6dJkqgCD2nadMyEMMFZxaKdbbd5TFteCExCoB7lc_HpqkywrwQeub0gHSi2LxY
  VITE_APP_USE_EMULATOR: true
  CYPRESS_PROJECT_ID: oq14r7
  SKIP_PREFLIGHT_CHECK: true
  CI: false

on:
  push:
    branches:
      - master
      - vite
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - run: npm install -g firebase-tools
      - name: Build the server
        run: firebase emulators:exec --import=./testdata --project ${{ env.VITE_APP_FIREBASE_PROJECT_ID }} 'npm run build'
      - name: Run Firebase Emulator and Start Tests
        run: firebase emulators:exec --import=./testdata --project ${{ env.VITE_APP_FIREBASE_PROJECT_ID }} 'npm run test'
     