name: Cypress Tests

env:
  FIREBASE_PROJECT_ID: ${{ secrets.VITE_APP_FIREBASE_PROJECT_ID }}

on:
  push:
    branches:
      - master
      - vite
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - run: npm install -g firebase-tools
      - name: Run Firebase Emulator
        run: firebase emulators:start --import=testdata --project AIzaSyC_va_jZUMV13i7--ni9J6Sn-2EHYyIdP8
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
