name: Cypress Tests

env:
  VITE_APP_FIREBASE_API_KEY: ${{ secrets.VITE_APP_FIREBASE_API_KEY }}
  VITE_APP_FIREBASE_PROJECT_ID: ${{ secrets.VITE_APP_FIREBASE_PROJECT_ID }}
  VITE_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_APP_FIREBASE_MESSAGING_SENDER_ID }}
  VITE_APP_FIREBASE_APP_ID: ${{ secrets.VITE_APP_FIREBASE_APP_ID }}
  VITE_APP_FIREBASE_MEASUREMENTID: ${{ secrets.VITE_APP_FIREBASE_MEASUREMENTID }}
  VITE_APP_FIREBASE_FCM_VAPID_KEY: ${{ secrets.VITE_APP_FIREBASE_FCM_VAPID_KEY }}
  VITE_APP_AUTH_DOMAIN: ${{ secrets.VITE_APP_AUTH_DOMAIN }}
  VITE_APP_DATABASE_URL: ${{secrets.VITE_APP_DATABASE_URL}}
  CYPRESS_PROJECT_ID: oq14r7
  SKIP_PREFLIGHT_CHECK: true
  CI: false

on:
  push:
    branches:
      - master
      - vite
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Setup Node
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 14
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - run: npm install -g firebase-tools
      - name: Build the server
        run: npm run build
      - name: Start the server
        run: npm run dev
      - name: Run Firebase Emulator
        run: firebase emulators:exec 'npm run cy:run' --import=testdata --project ${{ env.VITE_APP_FIREBASE_PROJECT_ID }} 
      # - name: Cypress install
      #   run: npm install --legacy-peer-deps
      # - name: Cypress run tests
      #   uses: cypress-io/github-action@v2
      #   with:
      #     install: false
      #     build: npm run build
      #     start: npm run dev
      #     command: npm run cy:run
      #     browser: chrome